company_name: GoTest
project_name: TestPr

info_output:
  - gui: on
  - console: on

is_check_cycle: on

# live load
integration:
  prometheus: on


round_result:
   status: on
   number_of_decimal_places: 5